---
- name: Backup junos configurations
  hosts: junos # parent group
  gather_facts: false
  connection: ansible.netcommon.netconf
  # connection: ansible.netcommon.network_cli
  
  vars:
    ansible_network_os: junos

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      run_once: true
      delegate_to: localhost

  tasks:
    - name: Collect running configs and write to a file
      ansible.builtin.import_role:
        name: role-juniper-config-backup
      vars:
        _backup_: true
        _tmp_root_dir_: "{{ tmp_base_dir }}"
        _local_file_path_: "{{ tmp_base_dir }}/{{ git_repo_subdir_path }}/{{ config_backup_file_name }}"